// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDD-I28geWGcaeUtdAkt-i9oT1cUD9pUo',
    appId: '1:913621167791:android:7f3f8b82c19e3cf13dee5a',
    messagingSenderId: '913621167791',
    projectId: 'discover-b3c18',
    storageBucket: 'discover-b3c18.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaqEDEHbybnoT_6p5kOQ83ovmxAa2ZYJk',
    appId: '1:913621167791:ios:7ebc6d885e8d6d3a3dee5a',
    messagingSenderId: '913621167791',
    projectId: 'discover-b3c18',
    storageBucket: 'discover-b3c18.firebasestorage.app',
    iosClientId: '913621167791-n3u6e1v8tuagq7oeppbfrma72bdn8t3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.testPackegs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDU2vGDZOxLc2OfZFR8ZBjeLUdfyvQy6c',
    appId: '1:913621167791:web:6ae6a592abbfa29c3dee5a',
    messagingSenderId: '913621167791',
    projectId: 'discover-b3c18',
    authDomain: 'discover-b3c18.firebaseapp.com',
    storageBucket: 'discover-b3c18.firebasestorage.app',
  );
}
